[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "@arbitrum/token-bridge-contracts/=lib/token-bridge-contracts/contracts/",
  "@arbitrum/nitro-contracts/=lib/nitro/contracts/",
  "forge-std/=lib/forge-std/src/"
]
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4
